# Generated by Django 3.1.4 on 2021-02-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0002_auto_20210201_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.category', verbose_name='سرشاخه'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(validators=[myblog.validators.check_phone_number], verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='تصوير پروفايل')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
