# Generated by Django 3.1.4 on 2021-02-01 16:56

from django.db import migrations, models
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210201_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.BigIntegerField(validators=[myblog.validators.check_phone_number], verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='تصوير پروفايل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
