# Generated by Django 3.1.4 on 2021-02-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0004_auto_20210201_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(validators=[myblog.validators.check_phone_number], verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='تصوير پروفايل')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
