# Generated by Django 3.1.4 on 2021-02-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20210201_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
