# Generated by Django 3.1.4 on 2021-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_delete_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_confirm', 'Can confirm all comments')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('change_all_activation', 'Can change all posts activations'), ('change_activation', 'Can change just one activation'), ('can_confirm', 'Can confirm all posts')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='مجاز'),
        ),
    ]
