# Generated by Django 3.1.4 on 2021-02-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20210202_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_confirm_comments', 'Can confirm all comments')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_confirm_posts', 'Can confirm all posts'), ('change_all_activation', 'Can change all posts activations'), ('change_activation', 'Can change just one activation')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
