# Generated by Django 3.1.4 on 2021-02-02 19:19

from django.db import migrations, models
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20210202_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, help_text='برچسب ها با# آغاز مي\u200cشوند و فقط شامل حروف الفبا و _ مي\u200cشوند.برچسب\u200cها را با فاصله از هم جدا كنيد', max_length=2000, validators=[myblog.validators.check_tag], verbose_name='برچسب'),
        ),
    ]
