# Generated by Django 3.1.4 on 2021-02-02 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0009_auto_20210202_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, null=True, validators=[myblog.validators.check_phone_number], verbose_name='شماره تلفن')),
                ('image', models.ImageField(null=True, upload_to='posts_img', verbose_name='تصوير پروفايل')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
