# Generated by Django 3.1.4 on 2021-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_userextrainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts_img', verbose_name='تصوير'),
        ),
    ]
