# Generated by Django 3.1.4 on 2021-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20210203_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts_img', verbose_name='تصوير'),
        ),
    ]
