# Generated by Django 3.1.4 on 2021-02-09 17:18

from django.db import migrations, models
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20210205_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='برچسب ها با# آغاز مي\u200cشوند و فقط شامل حروف الفبا و _ مي\u200cشوند. برچسب\u200cها را با فاصله از هم جدا كنيد', max_length=30, validators=[myblog.validators.check_tag])),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, to='myblog.Tag'),
        ),
    ]
