# Generated by Django 3.1.4 on 2021-02-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20210209_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(to='myblog.Tag', verbose_name='برچسب'),
        ),
    ]
