# Generated by Django 3.1.4 on 2021-02-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20210210_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='label',
            new_name='tag',
        ),
    ]
