# Generated by Django 3.1.4 on 2021-02-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_auto_20210213_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='name',
        ),
    ]
