# Generated by Django 3.1.4 on 2021-02-12 21:02

from django.db import migrations, models
import myblog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_auto_20210213_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[myblog.validators.check_tag]),
        ),
    ]
