# Generated by Django 3.1.4 on 2021-02-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0021_auto_20210213_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='label',
        ),
    ]
