# Generated by Django 3.1.4 on 2021-02-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_auto_20210213_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(help_text='برچسب ها با# آغاز مي\u200cشوند و فقط شامل حروف الفبا و _ مي\u200cشوند. برچسب\u200cها را با فاصله از هم جدا كنيد', null=True, to='myblog.Tag', verbose_name='برچسب'),
        ),
    ]
