# Generated by Django 3.1.4 on 2021-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_auto_20210215_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=400, verbose_name='متن نظر'),
        ),
    ]
