# Generated by Django 3.1.4 on 2021-02-22 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0024_auto_20210219_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecommentlog',
            unique_together={('comment', 'user')},
        ),
    ]
