# Generated by Django 3.1.4 on 2021-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0025_auto_20210223_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecommentlog',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ و زمان واكنش'),
        ),
    ]
