# Generated by Django 3.1.4 on 2021-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0026_likecommentlog_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecommentlog',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ و زمان واكنش'),
        ),
    ]
