# Generated by Django 3.1.4 on 2021-02-23 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_auto_20210223_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecommentlog',
            name='date_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ و زمان نظر'),
            preserve_default=False,
        ),
    ]
